services:
  gharkhoj.api:
    image: ${DOCKER_REGISTRY-}gharkhojapi
    build:
      context: .
      dockerfile: src/GharKhoj.Api/Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://gharkhoj.aspire:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    depends_on:
      - gharkhoj.db
      - gharkhoj.idp
      - gharkhoj.cache
      - gharkhoj.aspire
      
  gharkhoj.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=9d9dfbfbfdfd@S
      - MSSQL_PID=Developer
    volumes:
      - ./.containers/database-data:/var/opt/mssql/data
      - ./.containers/database-logs:/var/opt/mssql/logs
    ports:
      - "1433:1433"

  gharkhoj.idp:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=satoox
      - KEYCLOAK_ADMIN_PASSWORD=9d9dfbfbfdfd@S
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files/cipher-realm-export.json:/opt/keycloak/data/import/realm.json
    ports:
      - "18080:8080"

  gharkhoj.cache:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  gharkhoj.aspire:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - "18888:18888"
